// <auto-generated />
using System;
using FCG.Domain.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCG.Domain.Data.Migrations.Default
{
    [DbContext(typeof(FcgDbContext))]
    [Migration("20251029051058_FcgDbContext primeira migration")]
    partial class FcgDbContextprimeiramigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fcg")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CartId", "GameId")
                        .IsUnique();

                    b.ToTable("CartItems", "fcg");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Carts", "fcg");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EAN")
                        .IsUnique();

                    b.ToTable("Games", "fcg");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FCG.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players", "fcg");
                });

            modelBuilder.Entity("FCG.Domain.Entities.GalleryGame", b =>
                {
                    b.HasBaseType("FCG.Domain.Entities.Game");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.ToTable("GalleryGames", "fcg");
                });

            modelBuilder.Entity("FCG.Domain.Entities.LibraryGame", b =>
                {
                    b.HasBaseType("FCG.Domain.Entities.Game");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.HasIndex("PlayerId");

                    b.ToTable("LibraryGames", "fcg");
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("FCG.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCG.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCG.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Cart", b =>
                {
                    b.HasOne("FCG.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FCG.Domain.Entities.GalleryGame", b =>
                {
                    b.HasOne("FCG.Domain.Entities.Game", null)
                        .WithOne()
                        .HasForeignKey("FCG.Domain.Entities.GalleryGame", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FCG.Domain.ValuesObjects.Promotion", "Promotion", b1 =>
                        {
                            b1.Property<Guid>("GalleryGameId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndOf")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndOf");

                            b1.Property<DateTime>("StartOf")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartOf");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Type");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Value");

                            b1.HasKey("GalleryGameId");

                            b1.ToTable("GalleryGames", "fcg");

                            b1.WithOwner()
                                .HasForeignKey("GalleryGameId");
                        });

                    b.Navigation("Promotion")
                        .IsRequired();
                });

            modelBuilder.Entity("FCG.Domain.Entities.LibraryGame", b =>
                {
                    b.HasOne("FCG.Domain.Entities.Game", null)
                        .WithOne()
                        .HasForeignKey("FCG.Domain.Entities.LibraryGame", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCG.Domain.Entities.Player", "Player")
                        .WithMany("Library")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Player", b =>
                {
                    b.Navigation("Library");
                });
#pragma warning restore 612, 618
        }
    }
}
