// <auto-generated />
using System;
using FCG.Domain.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCG.Domain.Data.Migrations.Default
{
    [DbContext(typeof(FcgDbContext))]
    [Migration("20251020233509_FcgDbContext primeira migration")]
    partial class FcgDbContextprimeiramigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fcg")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCG.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games", "fcg");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Players", "fcg");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Game", b =>
                {
                    b.HasOne("Player", null)
                        .WithMany("Library")
                        .HasForeignKey("PlayerId");

                    b.OwnsOne("Promotion", "Promotion", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndOf")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PromocaoFim");

                            b1.Property<DateTime>("StartOf")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PromocaoInicio");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("PromocaoTipo");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("PromocaoValor");

                            b1.HasKey("GameId");

                            b1.ToTable("Promotion", "fcg");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Promotion")
                        .IsRequired();
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("Library");
                });
#pragma warning restore 612, 618
        }
    }
}
